[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/projets/2020--pauline-mathis/index.html"
to = "/portraits/2020-pauline-mathis/"

[[redirects]]
from = "/portraits/2022-pauline-mathis/index.html"
to = "/portraits/2020-pauline-mathis/"

[[redirects]]
from = "/projets/index.html"
to = "/portraits/"

[[redirects]]
from = "/julie/index.html"
to = "/portraits/julie/"

[[redirects]]
from = "/projets/2023-yseult/index.html"
to = "/portraits/2023-yseult/"

[[redirects]]
from = "/projets/2020-pauline-mathis/index.html"
to = "/portraits/2020-pauline-mathis/"

